apiVersion: v1
entries:
  rpchart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-04-15T15:58:52.307908-05:00"
    description: A Helm chart for Kubernetes by Ramon Pizana
    digest: 5723381bb8eab652fea6fb36ccad65b580a6b3e261b8fa30ae4492d8a6539bde
    name: rpchart
    type: application
    urls:
    - rpchart-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-15T15:58:52.307525-05:00"
