apiVersion: v1
entries:
  rpchart:
  - apiVersion: v2
    appVersion: 1.16.1
    created: "2022-04-15T16:09:15.966334-05:00"
    description: A Helm chart for Kubernetes by Ramon Pizana
    digest: 9904abd5bb64c749a55c2e73a3fc84da4aae2de79e75dc43252b1bc012a489ed
    name: rpchart
    type: application
    urls:
    - rpchart-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-04-15T16:09:15.966082-05:00"
    description: A Helm chart for Kubernetes by Ramon Pizana
    digest: 5723381bb8eab652fea6fb36ccad65b580a6b3e261b8fa30ae4492d8a6539bde
    name: rpchart
    type: application
    urls:
    - rpchart-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-15T16:09:15.965651-05:00"
